/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ufgd.redes.views.components;

import java.awt.Color;
import ufgd.redes.views.JanelaMain;
import ufgd.redes.views.PanelConversa;

/**
 *
 * @author franco
 */
public class TituloAbas extends javax.swing.JPanel {
    JanelaMain contexto;
    PanelConversa panel;
    /**
     * Creates new form PaneTituloAbas
     * @param contexto
     * @param panel
     * @param titulo
     */
    public TituloAbas(JanelaMain contexto,PanelConversa panel, String titulo) {
        initComponents();
        this.contexto= contexto;
        this.panel = panel;
        labelTitulo.setText(titulo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelTitulo = new javax.swing.JLabel();
        btFechar = new javax.swing.JButton();

        setBackground(java.awt.Color.white);
        setOpaque(false);

        labelTitulo.setFont(new java.awt.Font("Purisa", 0, 18)); // NOI18N
        labelTitulo.setText("titulo");

        btFechar.setBackground(new java.awt.Color(254, 254, 254));
        btFechar.setFont(new java.awt.Font("Purisa", 1, 11)); // NOI18N
        btFechar.setForeground(new java.awt.Color(64, 60, 60));
        btFechar.setText("X");
        btFechar.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btFechar.setBorderPainted(false);
        btFechar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btFecharMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btFecharMouseExited(evt);
            }
        });
        btFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btFecharActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btFechar, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(btFechar, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btFecharActionPerformed
        contexto.fecharConversa(panel, labelTitulo.getText());
    }//GEN-LAST:event_btFecharActionPerformed

    private void btFecharMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btFecharMouseEntered
        btFechar.setOpaque(true);
        btFechar.setBackground(Color.red);
        
    }//GEN-LAST:event_btFecharMouseEntered

    private void btFecharMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btFecharMouseExited
        btFechar.setOpaque(false);
        btFechar.setBackground(Color.white);
    }//GEN-LAST:event_btFecharMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btFechar;
    private javax.swing.JLabel labelTitulo;
    // End of variables declaration//GEN-END:variables
}
