/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ufgd.redes;

import java.util.HashMap;
import java.util.Map;
import ufgd.redes.model.Usuario;
import static ufgd.redes.util.Util.getIP;
/**
 *
 * @author franco
 */
public class JanelaMain extends javax.swing.JFrame {
    /**
     * Usuario atual.
     */
    Usuario eu;
    
    /**
     * Ip do servidor.
     */
    String ip_servidor = "locahost";
    
    /**
     * Guarda em memória quais abas estão abertas.
     * Chave: username, Integer: indice da aba
     */
    Map<String ,Integer> conversasAbertas; 
    
    /**
     * Creates new form JanelaMain
     * @param username
     */
    public JanelaMain(String username) {
        initComponents();
        conversasAbertas = new HashMap();
        eu = new Usuario();
        eu.setNome(username);
        eu.setIp(getIP());
        carregarListaContatos();
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane = new javax.swing.JTabbedPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListContatos = new javax.swing.JList();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Pombo");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jTabbedPane.setFont(new java.awt.Font("Droid Sans", 0, 18)); // NOI18N

        jListContatos.setFont(new java.awt.Font("Droid Sans", 0, 18)); // NOI18N
        jListContatos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jListContatosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jListContatos);

        jLabel1.setFont(new java.awt.Font("Droid Sans", 0, 18)); // NOI18N
        jLabel1.setText("<html>Contatos</html>");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addComponent(jTabbedPane))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1)
                .addGap(6, 6, 6))
        );

        setSize(new java.awt.Dimension(668, 489));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        System.exit(1);
    }//GEN-LAST:event_formWindowClosed
    
    /**
     * Carrega lista de Contatos ativos
     */
    private void carregarListaContatos(){
        jListContatos.setModel(new javax.swing.AbstractListModel() {
            Usuario[] contatos = {
                new Usuario("Joao","192.168.0.22"),
                new Usuario("Adão","192.168.0.24"),
                new Usuario("Maria","192.168.0.31"),
                new Usuario("Joana","192.168.0.40"),
            };
            public int getSize() { return contatos.length; }
            public Object getElementAt(int i) { return contatos[i]; }
        });
    }
    //Listener de clique encima de um usuario na lista
    private void jListContatosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jListContatosMouseClicked
        Usuario contato = (Usuario)jListContatos.getSelectedValue();
        //verifica se ja existe alguma aba aberta deste usuario
        if(conversasAbertas.containsKey(contato.getNome())){
            jTabbedPane.setSelectedIndex(conversasAbertas.get(contato.getNome()));//recupera indice da aba e seleciona aba da conversa
        }//se não existe aba aberta é preciso criar nova aba
        else{
            jTabbedPane.addTab(contato.getNome(), new PanelConversa(eu, contato));
            jTabbedPane.setSelectedIndex(jTabbedPane.getTabCount()-1);
            //guarda informações da aba na lista de conversas abertas
            conversasAbertas.put(contato.getNome(), jTabbedPane.getSelectedIndex());
        }
    }//GEN-LAST:event_jListContatosMouseClicked

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JList jListContatos;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane;
    // End of variables declaration//GEN-END:variables
}
