/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ufgd.redes;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.text.BadLocationException;
import javax.swing.text.html.HTMLDocument;
import javax.swing.text.html.HTMLEditorKit;
import ufgd.redes.model.Usuario;

/**
 *
 * @author franco
 */
public class PanelConversa extends javax.swing.JPanel {

    private Usuario contato;
    private Usuario eu;
    private String textoEu;
    private String textoContato;
    
    //ferramentas de ediçao do EditorPane, painel de conversas
    private HTMLEditorKit kit;
    private HTMLDocument doc;
    /**
     * Creates new form PanelConversa
     */
    public PanelConversa(Usuario eu, Usuario contato) {
        initComponents();
        this.contato=contato;
        this.eu = eu;
        //formatação dos textos de saída
        textoEu = "<b color=blue>Você disse:</b>    ";
        //String cor = gerarCor();
        textoContato = contato.getNome()+" disse:    ";
        
        //configurar  editorPane de conversas
        kit = new HTMLEditorKit();
        doc = new HTMLDocument();
        jEditorPaneConversa.setEditorKit(kit);
        jEditorPaneConversa.setDocument(doc);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextFieldEntrada = new javax.swing.JTextField();
        jButtonEnviar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jEditorPaneConversa = new javax.swing.JEditorPane();

        setBackground(new java.awt.Color(246, 246, 246));

        jTextFieldEntrada.setFont(new java.awt.Font("Droid Sans", 0, 24)); // NOI18N

        jButtonEnviar.setFont(new java.awt.Font("Droid Sans", 0, 20)); // NOI18N
        jButtonEnviar.setText("Enviar");
        jButtonEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEnviarActionPerformed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ufgd/redes/resource/img/file64.png"))); // NOI18N

        jScrollPane1.setViewportView(jEditorPaneConversa);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldEntrada, javax.swing.GroupLayout.DEFAULT_SIZE, 405, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonEnviar, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 302, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextFieldEntrada)
                    .addComponent(jButtonEnviar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(6, 6, 6))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEnviarActionPerformed
        String msg = jTextFieldEntrada.getText().replaceAll("^\\s+", "");;
        if(msg.isEmpty())
            return;
        msg = textoEu+msg;
        
        //adiciona texto na tela
        try {
            kit.insertHTML(doc, doc.getLength(), "\n"+msg, 0, 0, null);
        } catch (BadLocationException | IOException ex ) {
            Logger.getLogger(PanelConversa.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jButtonEnviarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonEnviar;
    private javax.swing.JEditorPane jEditorPaneConversa;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextFieldEntrada;
    // End of variables declaration//GEN-END:variables
}
