/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ufgd.redes.views;

import javax.swing.JFrame;
import ufgd.redes.interfaces.Contexto;

/**
 *
 * @author franco
 */
public class JanelaProfileImagens extends javax.swing.JDialog {

    Contexto contexto;
    /**
     * Creates new form JanelaProfileImagens
     * @param contexto
     */
    public JanelaProfileImagens(Contexto contexto) {
        super(new JFrame(),true);
        this.contexto = contexto;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btImage1 = new javax.swing.JButton();
        btImage2 = new javax.swing.JButton();
        btImage3 = new javax.swing.JButton();
        btImage5 = new javax.swing.JButton();
        btImage6 = new javax.swing.JButton();
        btImage7 = new javax.swing.JButton();
        btImage8 = new javax.swing.JButton();
        btImage9 = new javax.swing.JButton();
        btImage11 = new javax.swing.JButton();
        btImage12 = new javax.swing.JButton();
        btImage13 = new javax.swing.JButton();
        btImage14 = new javax.swing.JButton();
        btImage15 = new javax.swing.JButton();
        btImage17 = new javax.swing.JButton();
        btImage18 = new javax.swing.JButton();
        btImage19 = new javax.swing.JButton();
        btImage20 = new javax.swing.JButton();
        btImage16 = new javax.swing.JButton();
        btImage21 = new javax.swing.JButton();
        btImage22 = new javax.swing.JButton();
        btImage10 = new javax.swing.JButton();
        btImage23 = new javax.swing.JButton();
        btImage24 = new javax.swing.JButton();
        btImage25 = new javax.swing.JButton();
        labelTitulo = new javax.swing.JLabel();
        labelSair = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(java.awt.Color.white);
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        btImage1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ufgd/redes/utils/imagens/profiles/1.jpeg"))); // NOI18N
        btImage1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btImage1ActionPerformed(evt);
            }
        });

        btImage2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ufgd/redes/utils/imagens/profiles/3.jpeg"))); // NOI18N
        btImage2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btImage2ActionPerformed(evt);
            }
        });

        btImage3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ufgd/redes/utils/imagens/profiles/2.jpeg"))); // NOI18N
        btImage3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btImage3ActionPerformed(evt);
            }
        });

        btImage5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ufgd/redes/utils/imagens/profiles/4.jpeg"))); // NOI18N
        btImage5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btImage5ActionPerformed(evt);
            }
        });

        btImage6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ufgd/redes/utils/imagens/profiles/5.jpeg"))); // NOI18N
        btImage6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btImage6ActionPerformed(evt);
            }
        });

        btImage7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ufgd/redes/utils/imagens/profiles/8.jpeg"))); // NOI18N
        btImage7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btImage7ActionPerformed(evt);
            }
        });

        btImage8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ufgd/redes/utils/imagens/profiles/6.jpeg"))); // NOI18N
        btImage8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btImage8ActionPerformed(evt);
            }
        });

        btImage9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ufgd/redes/utils/imagens/profiles/7.jpeg"))); // NOI18N
        btImage9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btImage9ActionPerformed(evt);
            }
        });

        btImage11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ufgd/redes/utils/imagens/profiles/9.jpeg"))); // NOI18N
        btImage11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btImage11ActionPerformed(evt);
            }
        });

        btImage12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ufgd/redes/utils/imagens/profiles/10.jpeg"))); // NOI18N
        btImage12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btImage12ActionPerformed(evt);
            }
        });

        btImage13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ufgd/redes/utils/imagens/profiles/13.jpeg"))); // NOI18N
        btImage13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btImage13ActionPerformed(evt);
            }
        });

        btImage14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ufgd/redes/utils/imagens/profiles/11.jpeg"))); // NOI18N
        btImage14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btImage14ActionPerformed(evt);
            }
        });

        btImage15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ufgd/redes/utils/imagens/profiles/12.jpeg"))); // NOI18N
        btImage15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btImage15ActionPerformed(evt);
            }
        });

        btImage17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ufgd/redes/utils/imagens/profiles/14.jpeg"))); // NOI18N
        btImage17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btImage17ActionPerformed(evt);
            }
        });

        btImage18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ufgd/redes/utils/imagens/profiles/15.jpeg"))); // NOI18N
        btImage18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btImage18ActionPerformed(evt);
            }
        });

        btImage19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ufgd/redes/utils/imagens/profiles/26.jpeg"))); // NOI18N
        btImage19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btImage19ActionPerformed(evt);
            }
        });

        btImage20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ufgd/redes/utils/imagens/profiles/20.jpeg"))); // NOI18N
        btImage20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btImage20ActionPerformed(evt);
            }
        });

        btImage16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ufgd/redes/utils/imagens/profiles/17.jpeg"))); // NOI18N
        btImage16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btImage16ActionPerformed(evt);
            }
        });

        btImage21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ufgd/redes/utils/imagens/profiles/16.jpeg"))); // NOI18N
        btImage21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btImage21ActionPerformed(evt);
            }
        });

        btImage22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ufgd/redes/utils/imagens/profiles/18.jpeg"))); // NOI18N
        btImage22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btImage22ActionPerformed(evt);
            }
        });

        btImage10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ufgd/redes/utils/imagens/profiles/22.jpeg"))); // NOI18N
        btImage10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btImage10ActionPerformed(evt);
            }
        });

        btImage23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ufgd/redes/utils/imagens/profiles/23.jpeg"))); // NOI18N
        btImage23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btImage23ActionPerformed(evt);
            }
        });

        btImage24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ufgd/redes/utils/imagens/profiles/24.jpeg"))); // NOI18N
        btImage24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btImage24ActionPerformed(evt);
            }
        });

        btImage25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ufgd/redes/utils/imagens/profiles/25.jpeg"))); // NOI18N
        btImage25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btImage25ActionPerformed(evt);
            }
        });

        labelTitulo.setFont(new java.awt.Font("Purisa", 0, 20)); // NOI18N
        labelTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTitulo.setText("Imagens para o seu profile");

        labelSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ufgd/redes/utils/imagens/cross18.png"))); // NOI18N
        labelSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelSairMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(labelTitulo)
                        .addGap(27, 27, 27)
                        .addComponent(labelSair))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btImage8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btImage9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btImage7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btImage11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btImage12))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btImage14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btImage15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btImage13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btImage17)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btImage18))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btImage21)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btImage16)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btImage22)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btImage19)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btImage20))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btImage1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btImage3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btImage2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btImage5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btImage6)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btImage10)
                            .addComponent(btImage23)
                            .addComponent(btImage24)
                            .addComponent(btImage25))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(labelTitulo))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(labelSair, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btImage10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btImage23)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btImage24)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btImage25))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btImage6)
                            .addComponent(btImage5)
                            .addComponent(btImage3)
                            .addComponent(btImage2)
                            .addComponent(btImage1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btImage9)
                            .addComponent(btImage7)
                            .addComponent(btImage8)
                            .addComponent(btImage12)
                            .addComponent(btImage11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btImage15)
                            .addComponent(btImage13)
                            .addComponent(btImage14)
                            .addComponent(btImage18)
                            .addComponent(btImage17))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btImage16)
                            .addComponent(btImage22)
                            .addComponent(btImage21)
                            .addComponent(btImage20)
                            .addComponent(btImage19))))
                .addGap(42, 42, 42))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void labelSairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelSairMouseClicked
        dispose();
        dispose();
    }//GEN-LAST:event_labelSairMouseClicked

    private void btImage1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btImage1ActionPerformed
        contexto.alterarFoto("1.jpeg");
        dispose();
    }//GEN-LAST:event_btImage1ActionPerformed

    private void btImage3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btImage3ActionPerformed
        contexto.alterarFoto("2.jpeg");
        dispose();
    }//GEN-LAST:event_btImage3ActionPerformed

    private void btImage2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btImage2ActionPerformed
        contexto.alterarFoto("3.jpeg");
        dispose();
    }//GEN-LAST:event_btImage2ActionPerformed

    private void btImage5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btImage5ActionPerformed
        contexto.alterarFoto("4.jpeg");
        dispose();
    }//GEN-LAST:event_btImage5ActionPerformed

    private void btImage6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btImage6ActionPerformed
        contexto.alterarFoto("5.jpeg");
        dispose();
    }//GEN-LAST:event_btImage6ActionPerformed

    private void btImage10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btImage10ActionPerformed
        contexto.alterarFoto("22.jpeg");
        dispose();
    }//GEN-LAST:event_btImage10ActionPerformed

    private void btImage8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btImage8ActionPerformed
        contexto.alterarFoto("6.jpeg");
        dispose();
    }//GEN-LAST:event_btImage8ActionPerformed

    private void btImage9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btImage9ActionPerformed
        contexto.alterarFoto("7.jpeg");
        dispose();
    }//GEN-LAST:event_btImage9ActionPerformed

    private void btImage7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btImage7ActionPerformed
        contexto.alterarFoto("8.jpeg");
        dispose();
    }//GEN-LAST:event_btImage7ActionPerformed

    private void btImage11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btImage11ActionPerformed
        contexto.alterarFoto("9.jpeg");
        dispose();
    }//GEN-LAST:event_btImage11ActionPerformed

    private void btImage12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btImage12ActionPerformed
        contexto.alterarFoto("10.jpeg");
        dispose();
    }//GEN-LAST:event_btImage12ActionPerformed

    private void btImage23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btImage23ActionPerformed
        contexto.alterarFoto("23.jpeg");
        dispose();
    }//GEN-LAST:event_btImage23ActionPerformed

    private void btImage14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btImage14ActionPerformed
        contexto.alterarFoto("11.jpeg");
        dispose();
    }//GEN-LAST:event_btImage14ActionPerformed

    private void btImage15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btImage15ActionPerformed
        contexto.alterarFoto("12.jpeg");
        dispose();
    }//GEN-LAST:event_btImage15ActionPerformed

    private void btImage13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btImage13ActionPerformed
        contexto.alterarFoto("13.jpeg");
        dispose();
    }//GEN-LAST:event_btImage13ActionPerformed

    private void btImage17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btImage17ActionPerformed
        contexto.alterarFoto("14.jpeg");
        dispose();
    }//GEN-LAST:event_btImage17ActionPerformed

    private void btImage18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btImage18ActionPerformed
        contexto.alterarFoto("15.jpeg");
        dispose();
    }//GEN-LAST:event_btImage18ActionPerformed

    private void btImage24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btImage24ActionPerformed
        contexto.alterarFoto("24.jpeg");
        dispose();
    }//GEN-LAST:event_btImage24ActionPerformed

    private void btImage21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btImage21ActionPerformed
        contexto.alterarFoto("16.jpeg");
        dispose();
    }//GEN-LAST:event_btImage21ActionPerformed

    private void btImage16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btImage16ActionPerformed
        contexto.alterarFoto("17.jpeg");
        dispose();
    }//GEN-LAST:event_btImage16ActionPerformed

    private void btImage22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btImage22ActionPerformed
        contexto.alterarFoto("18.jpeg");
        dispose();
    }//GEN-LAST:event_btImage22ActionPerformed

    private void btImage19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btImage19ActionPerformed
        contexto.alterarFoto("26.jpeg");
        dispose();
    }//GEN-LAST:event_btImage19ActionPerformed

    private void btImage20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btImage20ActionPerformed
        contexto.alterarFoto("20.jpeg");
        dispose();
    }//GEN-LAST:event_btImage20ActionPerformed

    private void btImage25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btImage25ActionPerformed
        contexto.alterarFoto("25.jpeg");
        dispose();
    }//GEN-LAST:event_btImage25ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btImage1;
    private javax.swing.JButton btImage10;
    private javax.swing.JButton btImage11;
    private javax.swing.JButton btImage12;
    private javax.swing.JButton btImage13;
    private javax.swing.JButton btImage14;
    private javax.swing.JButton btImage15;
    private javax.swing.JButton btImage16;
    private javax.swing.JButton btImage17;
    private javax.swing.JButton btImage18;
    private javax.swing.JButton btImage19;
    private javax.swing.JButton btImage2;
    private javax.swing.JButton btImage20;
    private javax.swing.JButton btImage21;
    private javax.swing.JButton btImage22;
    private javax.swing.JButton btImage23;
    private javax.swing.JButton btImage24;
    private javax.swing.JButton btImage25;
    private javax.swing.JButton btImage3;
    private javax.swing.JButton btImage5;
    private javax.swing.JButton btImage6;
    private javax.swing.JButton btImage7;
    private javax.swing.JButton btImage8;
    private javax.swing.JButton btImage9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelSair;
    private javax.swing.JLabel labelTitulo;
    // End of variables declaration//GEN-END:variables
}
